name: Build and Package Windows EXE

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --name "GIndexChecker" --windowed --icon=assets/gindexchecker2.ico --add-data "assets;assets" --noupx --clean src/main.py

      - name: Zip the GIndexChecker folder
        run: |
          cd dist
          powershell Compress-Archive -Path GIndexChecker -DestinationPath ../GIndexChecker-win.zip

      - name: Upload ZIP as release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: GIndexChecker-win.zip
